export const socialIcon = [
    {
      id: 1,
      tooltip:"Teligram",
      linkPath: "#",
      imgPath: "/assets/footerimges/socialicon/teligram.svg",
      alttext: "icon Img",
    },
    {
      id: 2,
      tooltip:"Gmail",
      linkPath: "#",
      imgPath: "/assets/commonimg/google.svg",
      alttext: "icon Img",
    },
    {
      id: 3,
      linkPath: "#",
      tooltip:"TronWalet",
      imgPath: "/assets/commonimg/tron.svg",
      alttext: "icon Img",
    },
    {
      id: 4,
      tooltip:"metamask",
      linkPath: "#",
      imgPath: "/assets/commonimg/metamask.svg",
      alttext: "icon Img",
    },
    {
      id: 5,
      tooltip:"Binance chain",
      linkPath: "#",
      imgPath: "/assets/commonimg/bnb.svg",
      alttext: "icon Img",
    },
    {
      id: 6,
      tooltip:"Coin98",
      linkPath: "#",
      imgPath: "/assets/commonimg/coin98.svg",
      alttext: "icon Img",
    },
    // {
    //   id: 7,
    //   tooltip:"tiktok",
    //   linkPath: "#",
    //   imgPath: "/assets/footerimges/socialicon/tikto.svg",
    //   alttext: "icon Img",
    // },
    // {
    //   id: 8,
    //   tooltip:"pinterest",
    //   linkPath: "#",
    //   imgPath: "/assets/footerimges/socialicon/pentirest.svg",
    //   alttext: "icon Img",
    // },
    // {
    //   id: 9,
    //   tooltip:"discord",
    //   linkPath: "#",
    //   imgPath: "/assets/footerimges/socialicon/discord.svg",
    //   alttext: "icon Img",
    // },
    // {
    //   id: 10,
    //   tooltip:"reddit",
    //   linkPath: "#",
    //   imgPath: '/assets/footerimges/socialicon/reddit.svg',
    //   alttext: "icon Img",
    // },
  ];