export { default as Navbar } from './layout/navbar';
export { default as Footer } from './layout/footer';
export { default as RightSidebar } from './layout/Right-sidebar';
export { default as Sidebar } from './layout/sidebar';
export { default as CustomSwitch } from './switch';
export { default as Logo } from './Logo';
export { default as HeaderComp } from './hero';
export { default as TopFeatures } from "./top-feature"
export { default as Statistics } from "./statistics"
export { default as GameCard } from "./game-card"
export { default as Games } from "./games"
export { default as DynamicSlider } from "./dynamicSlider"