import Head from 'next/head'
import React from 'react'
import Layout from '../src/components/layout'

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Home sf</div>
    </>
  )
}

export default Home
